name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Değişiklikleri hangi branch'e iteklediğinizde deploy yapmasını istiyorsanız onu seçin.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Projenizde kullanılan Node.js versiyonunu burada belirtin.

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Build komutunuz farklıysa burada belirtin.

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # React projenizin build çıktısı buradaysa doğru konumu belirtin.
